language: node_js
services:
  - redis-server
sudo: required
dist: trusty
before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb
install:
  - npm install;
  - npm install travis-github-lint-status;
script:
  - ./node_modules/travis-github-lint-status/index.js
  - npm run test && bash <(curl -s https://codecov.io/bash)
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      mv config/config-ci.json config/config.json;
      retry -n 1 -- npm run regression-test;
    fi
env:
  - TB_API_SECRET=123 TB_API_KEY=123 SAUCE_USERNAME=opentok
addons:
  firefox: "latest"
  jwt:
    secure: "ZJYdMZDsBINdNmyj0mbK/qC11eKa80MACgiNWzy7HxtFuxYwEtkTD4zgGTfI8re7s3Va68dbxWSbhIW0iuZGRTddWMqTmp+Aw6d+zgilO8G7ps0VRy1imRWvXAoTx1UFgV5DCHX/uUpejjF/YB18jZ9qKOIzTS8F5uKnFV1eyL+arMfUE8aie/3nR7uGvlpPhmS6A1rSrAXXb16f8bKv/X2Op5tg9z5nBpOLAs4e12v2plL+9LFD1Fu31KdGeonp97QBskxPpm0uZi7YSSsnbcCpIRshXJtFMKF0+y2hCxesbpFJXLpE8kcpEenVyxuGZpdhkguIgc1WGLDAJw4pdc/ro7xOnFtDMTRv+B7NU6xPFJiszQZGE29yIJDgIWKQCj+y+Yv4oCM848YuMvp7cJ39RkaOpDBgpJHBa0iWBcEjX21Id486oCTzqi56UCumrEuI8znWoR6krUM1m4I9rHcCZAKDYtdu25Cuv74iq8/OgGuVyiZ27dWda4TvHnsmm0Rm373mlFEdQ1y85qWVoeY9U4yUVeoCd3NMn1U7PSysahc1OXuaprm/1n0/K/qjv0bzRp9UGak63BBJ+wixEBUrcjjVfiJ4YRfF1lJkWJKv5uyv3L0OS2TqUGvieO7KSEPJ/LW0FcIwc2Mq3nMdyEb0oc9vkJ0Pnl/kQqs+uX0="
